// config.ts
// Minimum-friction configuration loader.
//
// REQUIRED (just two — the data sink):
//   SUPABASE_URL
//   SUPABASE_SERVICE_ROLE_KEY
//
// EVERYTHING ELSE IS OPTIONAL with documented degradation:
//   REDIS_URL              — falls back to in-process queue (single machine, no persistence)
//   HMAC_SHARED_SECRET     — REQUIRED in production for /enqueue auth; in dev, a
//                             random secret is auto-generated on boot and logged.
//                             The supabase scraper-enqueue EF must use the same value.
//   GEMINI_API_KEY         — signal compose falls back to rule-based scoring
//   GITHUB_TOKEN           — GitHub worker uses anon API (60 req/h instead of 5000)
//   REDDIT_CLIENT_ID/SECRET — Reddit worker uses anon API (10 req/min instead of 60)
//   MEILISEARCH_HOST/KEY   — Frontend search panel disabled; scraper skips indexing
//
// Production checklist: set SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, HMAC_SHARED_SECRET.
// Everything else can be added incrementally as you need richer signal.

import { randomBytes } from 'node:crypto';

// Only two truly required keys — everything else has a graceful fallback.
const REQUIRED_KEYS = [
  'SUPABASE_URL',
  'SUPABASE_SERVICE_ROLE_KEY',
] as const;

export type RequiredKey = typeof REQUIRED_KEYS[number];

const r = (key: RequiredKey): string => process.env[key] ?? '';
const optional = (key: string, fallback = ''): string => process.env[key] ?? fallback;

const NODE_ENV = optional('NODE_ENV', 'development');
const IS_PRODUCTION = NODE_ENV === 'production';

// Auto-generate HMAC secret in dev if not provided. Production still requires
// the operator to set it (so the supabase EF can sign requests with the same).
function resolveHmacSecret(): { value: string; generated: boolean } {
  const supplied = optional('HMAC_SHARED_SECRET', '');
  if (supplied) return { value: supplied, generated: false };
  if (IS_PRODUCTION) return { value: '', generated: false }; // empty → /enqueue refuses all calls
  // Dev fallback — random 64-char hex secret regenerated on each boot
  const dev = randomBytes(32).toString('hex');
  return { value: dev, generated: true };
}

const hmacResolution = resolveHmacSecret();

export const config = {
  port:     parseInt(optional('PORT', '8080'), 10),
  nodeEnv:  NODE_ENV,
  logLevel: optional('LOG_LEVEL', 'info'),

  supabase: {
    url:            r('SUPABASE_URL'),
    serviceRoleKey: r('SUPABASE_SERVICE_ROLE_KEY'),
  },

  redis: {
    /** Empty string → in-process queue mode. */
    url: optional('REDIS_URL', ''),
  },

  hmac: {
    sharedSecret: hmacResolution.value,
    /** True when the secret was auto-generated for dev. Server logs it once at startup. */
    autoGenerated: hmacResolution.generated,
  },

  gemini: {
    apiKey: optional('GEMINI_API_KEY'),
  },

  meilisearch: {
    host:   optional('MEILISEARCH_HOST', ''),
    apiKey: optional('MEILISEARCH_API_KEY', ''),
    enabled: Boolean(optional('MEILISEARCH_HOST', '')),
  },

  github: {
    token: optional('GITHUB_TOKEN'),
  },

  reddit: {
    clientId:     optional('REDDIT_CLIENT_ID'),
    clientSecret: optional('REDDIT_CLIENT_SECRET'),
    userAgent:    optional('REDDIT_USER_AGENT', 'humansheild-scraper/0.1'),
    enabled: Boolean(optional('REDDIT_CLIENT_ID') && optional('REDDIT_CLIENT_SECRET')),
  },

  concurrency: {
    http:    parseInt(optional('QUEUE_CONCURRENCY_HTTP', '10'),    10),
    browser: parseInt(optional('QUEUE_CONCURRENCY_BROWSER', '1'),  10),
  },
} as const;

export type Config = typeof config;

// ── Validation surface ──────────────────────────────────────────────────────

export interface ConfigStatus {
  ok:        boolean;
  missing:   RequiredKey[];
  /** Paste-ready fly secrets command, empty when nothing is missing. */
  flyHint:   string;
  /** Production environments require HMAC explicitly; this flags that case. */
  hmacMissingInProd: boolean;
  /** Optional features that are degraded due to missing config. */
  degraded:  Array<{ feature: string; reason: string }>;
}

export function validateConfig(): ConfigStatus {
  const missing = REQUIRED_KEYS.filter(k => !process.env[k]);
  const hmacMissingInProd = IS_PRODUCTION && !process.env.HMAC_SHARED_SECRET;

  const degraded: Array<{ feature: string; reason: string }> = [];
  if (!config.redis.url) {
    degraded.push({ feature: 'queue', reason: 'in-process mode (no Redis) — single-machine, no persistence' });
  }
  if (!config.gemini.apiKey) {
    degraded.push({ feature: 'signal_compose_llm', reason: 'GEMINI_API_KEY missing — rule-based composition only' });
  }
  if (!config.meilisearch.enabled) {
    degraded.push({ feature: 'event_search', reason: 'MEILISEARCH_HOST missing — frontend search panel disabled' });
  }
  if (!config.github.token) {
    degraded.push({ feature: 'github_worker', reason: 'GITHUB_TOKEN missing — anonymous API (60 req/h)' });
  }
  if (!config.reddit.enabled) {
    degraded.push({ feature: 'reddit_worker', reason: 'REDDIT_CLIENT_ID/SECRET missing — anonymous API (10 req/min)' });
  }
  if (hmacResolution.generated) {
    degraded.push({ feature: 'hmac', reason: 'HMAC_SHARED_SECRET auto-generated for dev — set explicitly for production' });
  }

  const flyHint = missing.length === 0 && !hmacMissingInProd
    ? ''
    : 'fly secrets set ' +
        [...missing, ...(hmacMissingInProd ? ['HMAC_SHARED_SECRET'] : [])]
          .map(k => `${k}=<value>`).join(' ');

  return {
    ok: missing.length === 0 && !hmacMissingInProd,
    missing,
    flyHint,
    hmacMissingInProd,
    degraded,
  };
}

/**
 * Prints a clear startup status with the missing keys (if any) and the list
 * of features running in degraded mode. Returns true when minimum config is
 * present.
 */
export function logConfigStatus(): boolean {
  const status = validateConfig();
  const bar = '═'.repeat(74);

  if (!status.ok) {
    console.error('');
    console.error(`╔${bar}╗`);
    console.error('║  Scraper cannot start workers — minimum config missing.              ║');
    console.error('║  HTTP server is still bound so /health can report the misconfig.     ║');
    console.error(`╚${bar}╝`);
    console.error('');
    console.error('Missing required:');
    for (const k of status.missing) console.error(`  ✗ ${k}`);
    if (status.hmacMissingInProd) {
      console.error(`  ✗ HMAC_SHARED_SECRET (required in production; dev auto-generates one)`);
    }
    console.error('');
    console.error('Fix on Fly.io with:');
    console.error(`  ${status.flyHint}`);
    console.error('');
    console.error('Or locally, copy artifacts/scraper/.env.example to .env.local and fill in.');
    console.error('');
    return false;
  }

  console.log('[config] minimum required env vars present ✓');

  // HMAC auto-gen notice — print the value so operators can paste it into the
  // supabase EF secrets if they're testing the full round-trip locally.
  if (config.hmac.autoGenerated) {
    console.log('');
    console.log('[config] HMAC_SHARED_SECRET auto-generated for dev:');
    console.log(`  ${config.hmac.sharedSecret}`);
    console.log('[config] Use the same value in supabase secrets if testing the EF round-trip.');
    console.log('');
  }

  if (status.degraded.length > 0) {
    console.log('[config] running with degraded features:');
    for (const d of status.degraded) {
      console.log(`  • ${d.feature}: ${d.reason}`);
    }
  }

  return true;
}
