// InactionCostCard.tsx — v audit UX
//
// Renders the "cost of waiting" card at the bottom of Summary tab.
// Data source: result.sixMonthInactionConsequence (string | null)
// Generated by: ensembleOrchestrator → LLM field, falls back to scenarioNarrativeEngine
//
// Design: dark amber, stark warning framing.
// Positioned as the final section of SummaryTab — after all other cards —
// so users leave the tab with a clear understanding of what NOT acting means.

import React from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle } from 'lucide-react';

export interface InactionCostCardProps {
  consequence: string;
}

export const InactionCostCard: React.FC<InactionCostCardProps> = ({ consequence }) => {
  if (!consequence || consequence.trim().length === 0) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.22, duration: 0.3 }}
      style={{
        borderRadius: '14px',
        background: 'rgba(251,191,36,0.06)',
        border: '1px solid rgba(251,191,36,0.25)',
        padding: '14px 16px',
      }}
    >
      {/* Header row */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
        <AlertTriangle size={13} style={{ color: 'var(--color-amber-text)', flexShrink: 0 }} />
        <span
          style={{
            fontSize: '0.6875rem',
            fontFamily: 'var(--font-mono)',
            fontWeight: 800,
            letterSpacing: '0.12em',
            textTransform: 'uppercase',
            color: 'var(--color-amber-text)',
          }}
        >
          ⚠ The cost of waiting
        </span>
      </div>

      {/* Consequence text */}
      <p
        style={{
          fontSize: '0.825rem',
          lineHeight: 1.55,
          color: 'var(--alpha-text-70)',
          margin: 0,
        }}
      >
        {consequence}
      </p>

      {/* CTA nudge */}
      <p
        style={{
          marginTop: 8,
          fontSize: '0.72rem',
          color: 'rgba(251,191,36,0.65)',
          lineHeight: 1.4,
        }}
      >
        Open the <strong style={{ color: 'var(--color-amber-text)', fontWeight: 700 }}>Act Now</strong> tab to start your 7-day action sequence.
      </p>
    </motion.div>
  );
};

export default InactionCostCard;
